def city_array_ibge
  %W{"Pacaraima (RR)"
"Uruará (PA)"
"Mirassol (SP)"
"Coxim (MS)"
"Faina (GO)"
"Guanambi (BA)"
"Alvorada (RS)"
"Bom Sucesso (PR)"
"São Vicente do Seridó (PB)"
"Itapipoca (CE)"
"Barro Alto (BA)"
"Faxinal do Soturno (RS)"
"General Sampaio (CE)"
"Itapema (SC)"
"Redentora (RS)"
"Capinzal do Norte (MA)"
"Lajedão (BA)"
"Novorizonte (MG)"
"Vazante (MG)"
"Martinópolis (SP)"
"Seropédica (RJ)"
"Alvorada (TO)"
"Matos Costa (SC)"
"Croatá (CE)"
"Rio Espera (MG)"
"Américo Brasiliense (SP)"
"Piraquara (PR)"
"Igaratinga (MG)"
"Mirandópolis (SP)"
"Concórdia (SC)"
"Maravilhas (MG)"
"São Sebastião do Passé (BA)"
"Adustina (BA)"
"Cunhataí (SC)"
"São Benedito do Rio Preto (MA)"
"Malhada de Pedras (BA)"
"Brotas (SP)"
"Santa Cruz Cabrália (BA)"
"Delta (MG)"
"Currais Novos (RN)"
"Catalão (GO)"
"Itaperuçu (PR)"
"Anchieta (ES)"
"Jardinópolis (SC)"
"São João da Ponte (MG)"
"Fernando Prestes (SP)"
"Engenheiro Paulo de Frontin (RJ)"
"Mirassolândia (SP)"
"Lagoão (RS)"
"Capela (SE)"
"Ocara (CE)"
"São Domingos (SE)"
"Santa Maria da Boa Vista (PE)"
"Benedito Leite (MA)"
"Orizânia (MG)"
"Nilo Peçanha (BA)"
"Santo Antônio do Tauá (PA)"
"Carmo do Rio Verde (GO)"
"São Mamede (PB)"
"Conceição do Araguaia (PA)"
"Maetinga (BA)"
"Santa Isabel do Ivaí (PR)"
"Aripuanã (MT)"
"Cantagalo (RJ)"
"Diamante do Norte (PR)"
"São José do Divino (PI)"
"Calçoene (AP)"
"Pontalina (GO)"
"Paranaguá (PR)"
"Maragogi (AL)"
"Itapé (BA)"
"Itaberaí (GO)"
"Volta Redonda (RJ)"
"Itacurubi (RS)"
"Balneário Arroio do Silva (SC)"
"Palestina (AL)"
"Taquarivaí (SP)"
"Maximiliano de Almeida (RS)"
"Anchieta (ES)"
"Nova Bassano (RS)"
"São João da Canabrava (PI)"
"Ouvidor (GO)"
"Arara (PB)"
"Lagoa de Velhos (RN)"
"Chapecó (SC)"
"Serra Negra do Norte (RN)"
"Ubaitaba (BA)"
"Paraí (RS)"
"Marco (CE)"
"Saboeiro (CE)"
"Nova Alvorada (RS)"
"Encruzilhada do Sul (RS)"
"Malhada dos Bois (SE)"
"São Félix do Piauí (PI)"
"Monte Alegre do Piauí (PI)"
"Goiânia (GO)"
"Lucena (PB)"
"Igarassu (PE)"
"São Domingos do Cariri (PB)"
"Guarani d'Oeste (SP)"}

end
