def city_array_ibge
["Pacaraima  BR",
"Uruará  BR" ,
"Mirassol  BR" ,
"Coxim  BR" ,
"Faina  BR" ,
"Guanambi  BR" ,
"Alvorada  BR" ,
"Bom Sucesso  BR" ,
"São Vicente do Seridó  BR" ,
"Itapipoca  BR" ,
"Barro Alto  BR" ,
"Faxinal do Soturno  BR" ,
"General Sampaio  BR" ,
"Itapema  BR" ,
"Redentora  BR" ,
"Capinzal do Norte  BR" ,
"Lajedão  BR" ,
"Novorizonte  BR" ,
"Vazante  BR" ,
"Martinópolis  BR" ,
"Seropédica  BR" ,
"Alvorada  BR" ,
"Matos Costa  BR" ,
"Croatá  BR" ,
"Rio Espera  BR" ,
"Américo Brasiliense  BR" ,
"Piraquara  BR" ,
"Igaratinga  BR" ,
"Mirandópolis  BR" ,
"Concórdia  BR" ,
"Maravilhas  BR" ,
"São Sebastião do Passé  BR" ,
"Adustina  BR" ,
"Cunhataí  BR" ,
"São Benedito do Rio Preto  BR" ,
"Malhada de Pedras  BR" ,
"Brotas  BR" ,
"Santa Cruz Cabrália  BR" ,
"Delta  BR" ,
"Currais Novos  BR" ,
"Catalão  BR" ,
"Itaperuçu  BR" ,
"Anchieta  BR" ,
"Jardinópolis  BR" ,
"São João da Ponte  BR" ,
"Fernando Prestes  BR" ,
"Engenheiro Paulo de Frontin  BR" ,
"Mirassolândia  BR" ,
"Lagoão  BR" ,
"Itapé  BR" ,
"Itaberaí  BR" ,
"Volta Redonda  BR" ,
"Itacurubi  BR" ,
"Balneário Arroio do Silva  BR" ,
"Palestina  BR" ,
"Taquarivaí  BR" ,
"Maximiliano de Almeida  BR" ,
"Anchieta  BR" ,
"Nova Bassano  BR" ,
"São João da Canabrava  BR" ,
"Ouvidor  BR" ,
"Arara  BR" ,
"Lagoa de Velhos  BR" ,
"Chapecó  BR" ,
"Serra Negra do Norte  BR" ,
"Ubaitaba  BR" ,
"Paraí  BR" ,
"Marco  BR" ,
"Saboeiro  BR" ,
"Nova Alvorada  BR" ,
"Encruzilhada do Sul  BR" ,
"Malhada dos Bois  BR" ,
"São Félix do Piauí  BR" ,
"Monte Alegre do Piauí  BR" ,
"Goiânia  BR" ,
"Lucena  BR" ,
"Igarassu  BR" ,
"São Domingos do Cariri  BR" ,
"Guarani d'Oeste  BR" ,
"Garissa KE" ,
"Kakamega KE" ,
"Embu KE" ,
"Bungoma KE" ,
"Nyeri KE" ,
"Meru KE" ,
"Wajir KE" ,
"Naivasha KE" ,
"Voi KE" ,
"Nanyuki KE" ,
"Mavinga AO" ,
"Caxito AO" ,
"Luena AO" ,
"Nzeto AO" ,
"Camacupa AO" ,
"Luanga AO" ,
"Ambriz AO" ,
"Menongue AO" ,
"Camabatela AO" ,
"Uacu Cungo AO" ,
"Chimoio MZ" ,
"Quelimane MZ" ,
"Tete MZ" ,
"Xai-Xai MZ" ,
"Maxixe MZ" ,
"Inhambane MZ" ,
"Pemba MZ" ,
"Lichinga MZ" ,
"Dondo MZ" ,
"Cuamba MZ"]

end
